python test.py --config configs/base.json --generation "greedy"
# python test.py --config configs/base.json --generation "beam"
# python test.py --config configs/base.json --generation "sampling_topk"
# python test.py --config configs/base.json --generation "sampling_topp"
# python test.py --config configs/base.json --generation "sampling_topk_topp"